### ISSUE TITLE
geoip.dat 和 geosite.dat 路径不正确

### ISSUE THREAD

**Issue by H0u5er** [N4FA/homebrew-xray#1]
### 测试环境
MacOS 11.1
Homebrew 2.7.3
Homebrew/homebrew-core (git revision 6c8ef1; last commit 2021-01-12)
Homebrew/homebrew-cask (git revision 929df; last commit 2021-01-12)

### geo文件不存在
```
houser@Housers-MacBook-Pro ~ % xray --test --config /usr/local/etc/xray/config.json
Xray 1.2.1 (Xray, Penetrates Everything.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2021/01/12 20:28:40 [Info] main/json: Reading config: /usr/local/etc/xray/config.json
Failed to start: main: failed to load config files: [/usr/local/etc/xray/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: private > infra/conf: failed to load file: geoip.dat > infra/conf: failed to open file: geoip.dat > open /usr/local/bin/geoip.dat: no such file or directory
houser@Housers-MacBook-Pro ~ % 
houser@Housers-MacBook-Pro ~ % cd /usr/local/bin 
houser@Housers-MacBook-Pro bin % ls geo*
zsh: no matches found: geo*
```
### 测试1
在config.json文件中routing部分，移除调用geo到设置，执行xray --test --config /usr/local/etc/xray/config.json将不会报错，软件正常使用。

### 测试2
保留routing中geo的调用，把/usr/local/Cellar/xray-core/1.2.1/share/xray-core下的geoip.dat和geosite.dat，手动拷贝到报错提示的/usr/local/bin路径之后，执行xray --test --config /usr/local/etc/xray/config.json将不会报错，但是软件无法正常使用。

提交issue问问看有没有人遇到类似的问题，也希望作者看看打包有没有出问题🙏

**Comment by N4FA** [comment]
The default resource files are at  `/usr/local/share/xray-core`
Qv2ray is recommended client for MacOS, if you do not use MacOS as a  xray-core server.

**Comment by H0u5er** [comment]
The issue fixed after I download the Xray-core by another homebrew source.
